pull_request_rules:
  - name: assign and label scala-steward's PRs
    conditions:
      - author=scala-steward
    actions:
      assign:
        users: [tomasherman]
      label:
        add: [dependency-update]
  - name: Approve scala-steward patches
    conditions:
      - base=master
      - author=scala-steward
      - status-success=build (8, 2.12.10)
      - status-success=build (11, 2.12.10)
      - status-success=build (13, 2.12.10)
      - status-success=build (16, 2.12.10)
      - status-success=build (17, 2.12.10)
      - body~=labels:.*semver-spec-patch.*
    actions:
      review:
        type: APPROVE
  - name: automatic merge on CI success and review
    conditions:
      - base=master
      - "#changes-requested-reviews-by=0"
      - "#approved-reviews-by>=1"
      - status-success=build (8, 2.12.10)
      - status-success=build (11, 2.12.10)
      - status-success=build (13, 2.12.10)
      - status-success=build (16, 2.12.10)
      - status-success=build (17, 2.12.10)
    actions:
      merge:
        method: squash
        strict: true
      delete_head_branch:
        force: true
